import os
import datetime
import json
import requests
import cloudinary
import cloudinary.uploader
import google.generativeai as genai
from flask import Flask, render_template, request, jsonify
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO
import config
import qrcode
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import random
from openai import OpenAI

app = Flask(__name__)

# --- CONFIGURATION ---
app.config['UPLOAD_FOLDER'] = 'static/uploads'
app.config['PROCESSED_FOLDER'] = 'static/processed'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///realtime_agent.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Auto-detect URL
if os.environ.get('BASE_URL'):
    BASE_URL = os.environ.get('BASE_URL')
elif os.environ.get('RENDER_EXTERNAL_URL'):
    BASE_URL = os.environ.get('RENDER_EXTERNAL_URL')
else:
    BASE_URL="https://marketing-agent-yeej.onrender.com"

print(f"✅ QR CODES WILL POINT TO: {BASE_URL}")

COMPANY_ADDRESS = "KCE@Coimbatore | Call: +91 9385789540"
LOGO_PATH = "static/logo.png"

os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs(app.config['PROCESSED_FOLDER'], exist_ok=True)

db = SQLAlchemy(app)

# Setup APIs
try:
    cloudinary.config(
        cloud_name=config.CLOUDINARY_CLOUD_NAME, 
        api_key=config.CLOUDINARY_API_KEY, 
        api_secret=config.CLOUDINARY_API_SECRET
    )
    if config.GEMINI_API_KEY:
        genai.configure(api_key=config.GEMINI_API_KEY)
except Exception as e:
    print(f"⚠️ API Config Warning: {e}")

# --- DATABASE ---
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    platforms = db.Column(db.String(100))
    image_url = db.Column(db.String(300)) 
    caption = db.Column(db.Text)
    status = db.Column(db.String(50)) 
    scheduled_time = db.Column(db.String(50), nullable=True)
    impressions = db.Column(db.Integer, default=0)
    engagement = db.Column(db.Integer, default=0)
    clicks = db.Column(db.Integer, default=0)
    timestamp = db.Column(db.DateTime, default=datetime.datetime.utcnow)

with app.app_context():
    db.create_all()

# --- EMAIL ENGINE ---
def send_lead_email(name, phone, location, date, msg):
    try:
        email_msg = MIMEMultipart()
        email_msg['From'] = config.EMAIL_SENDER
        email_msg['To'] = config.EMAIL_RECEIVER
        email_msg['Subject'] = f"📅 New Booking: {date} - {name}"
        
        body = f"""
        <h2>New Booking Request</h2>
        <p><strong>Name:</strong> {name}</p>
        <p><strong>Phone:</strong> {phone}</p>
        <p><strong>Location:</strong> {location}</p>
        <p><strong>Date:</strong> {date}</p>
        <p><strong>Details:</strong> {msg}</p>
        <hr>
        <p><em>Generated by Marketing Agent</em></p>
        """
        email_msg.attach(MIMEText(body, 'html'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(config.EMAIL_SENDER, config.EMAIL_PASSWORD)
        server.send_message(email_msg)
        server.quit()
        return True
    except Exception as e:
        print(f"❌ EMAIL ERROR: {str(e)}")
        return False

# --- IMAGE ENGINE (POINTS TO WEBSITE) ---
class ImageHandler:
    def add_branding(self, img):
        base_width = 1080
        w_percent = (base_width / float(img.size[0]))
        h_size = int((float(img.size[1]) * float(w_percent)))
        img = img.resize((base_width, h_size), Image.Resampling.LANCZOS).convert("RGBA")
        
        overlay = Image.new('RGBA', img.size, (255, 255, 255, 0))
        draw = ImageDraw.Draw(overlay)
        
        try: 
            font = ImageFont.truetype("arial.ttf", 24)
            font_small = ImageFont.truetype("arial.ttf", 14)
        except: 
            font = ImageFont.load_default()
            font_small = ImageFont.load_default()

        # Logo
        if os.path.exists(LOGO_PATH):
            logo = Image.open(LOGO_PATH).convert("RGBA")
            target_w = int(base_width * 0.08)
            w_percent = (target_w / float(logo.size[0]))
            target_h = int((float(logo.size[1]) * float(w_percent)))
            logo = logo.resize((target_w, target_h), Image.Resampling.LANCZOS)
            overlay.paste(logo, (base_width - target_w - 30, 30), logo)

        # QR Code (Points to Website)
        qr = qrcode.QRCode(box_size=10, border=0)
        qr.add_data(f"{BASE_URL}/booking") 
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white").convert("RGBA")
        qr_img = qr_img.resize((90, 90))
        
        draw.rectangle([20, 20, 130, 140], fill=(255, 255, 255, 220))
        overlay.paste(qr_img, (30, 30))
        draw.text((32, 122), "SCAN TO BOOK", fill="black", font=font_small)

        # Address Pill
        text_bbox = draw.textbbox((0, 0), COMPANY_ADDRESS, font=font)
        pill_w = (text_bbox[2] - text_bbox[0]) + 60
        pill_x = (base_width - pill_w) / 2
        pill_y = h_size - 80
        draw.rectangle([pill_x, pill_y, pill_x + pill_w, pill_y + 50], fill=(0, 0, 0, 200))
        draw.text((pill_x + 30, pill_y + 12), COMPANY_ADDRESS, fill="white", font=font)
        
        return Image.alpha_composite(img, overlay)

    def process_request(self, file_storage, text_prompt):
        if file_storage:
            raw_path = os.path.join(app.config['UPLOAD_FOLDER'], file_storage.filename)
            file_storage.save(raw_path)
            img = Image.open(raw_path).convert("RGBA")
        else:
            seed = random.randint(1, 9999)
            enhanced_prompt = f"Professional corporate photography poster, {text_prompt}, minimalist style, clean background, no text, no typography, 8k resolution, cinematic lighting"
            api_url = f"https://image.pollinations.ai/prompt/{enhanced_prompt}?nologo=true&seed={seed}&width=1080&height=1350"
            res = requests.get(api_url)
            img = Image.open(BytesIO(res.content)).convert("RGBA")
        
        img = self.add_branding(img)
        filename = f"gen_{int(datetime.datetime.now().timestamp())}.png"
        save_path = os.path.join(app.config['PROCESSED_FOLDER'], filename)
        img.save(save_path, format="PNG")
        
        if config.CLOUDINARY_CLOUD_NAME:
            res = cloudinary.uploader.upload(save_path)
            return save_path, res['secure_url']
        return save_path, f"/{save_path}"

# --- CONTENT AGENT ---
class ContentAgent:
    def generate_captions(self, local_path, topic):
        try:
            print("🧠 Attempting Gemini Vision...")
            img = Image.open(local_path)
            model = genai.GenerativeModel('gemini-2.5-flash')
            prompt = f"Topic: {topic}. Analyze image. Generate 3 captions (linkedin, facebook, instagram). End with 'Scan QR to book!'."
            response = model.generate_content([prompt, img])
            return json.loads(response.text.replace("```json", "").replace("```", "").strip())
        except:
            return self.fallback(topic)

    def fallback(self, topic):
        try:
            client = OpenAI(api_key=config.GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")
            prompt = f"Write 3 photography marketing posts about '{topic}'. End with 'Scan QR to book!'."
            chat = client.chat.completions.create(messages=[{"role":"user", "content":prompt}], model="meta-llama/llama-guard-4-12b", response_format={"type":"json_object"})
            return json.loads(chat.choices[0].message.content)
        except:
            return {"linkedin": "Book Now", "facebook": "Book Now", "instagram": "Book Now"}

# --- BROADCASTER ---
class SocialBroadcaster:
    def post_to_apis(self, platforms, captions, image_url):
        results = {}
        # LinkedIn
        if 'linkedin' in platforms:
            try:
                author = config.LINKEDIN_PERSON_URN.replace("urn:li:member:", "urn:li:person:")
                url = "https://api.linkedin.com/v2/ugcPosts"
                headers = {"Authorization": f"Bearer {config.LINKEDIN_ACCESS_TOKEN}", "Content-Type": "application/json"}
                payload = {
                    "author": author, "lifecycleState": "PUBLISHED",
                    "specificContent": {
                        "com.linkedin.ugc.ShareContent": {
                            "shareCommentary": {"text": captions.get('linkedin', '')},
                            "shareMediaCategory": "ARTICLE",
                            "media": [{"status": "READY", "originalUrl": image_url, "title": {"text": "Post"}}]
                        }
                    },
                    "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"}
                }
                r = requests.post(url, headers=headers, json=payload)
                results['linkedin'] = "✅ Posted" if r.status_code == 201 else f"❌ Failed: {r.text}"
            except Exception as e: results['linkedin'] = str(e)

        # Facebook
        if 'facebook' in platforms:
            try:
                fb_url = f"https://graph.facebook.com/{config.FB_PAGE_ID}/photos"
                r = requests.post(fb_url, data={"url": image_url, "message": captions.get('facebook', ''), "access_token": config.FB_PAGE_ACCESS_TOKEN})
                results['facebook'] = "✅ Posted" if 'id' in r.json() else f"❌ Failed: {r.json()}"
            except Exception as e: results['facebook'] = str(e)

        # Instagram
        if 'instagram' in platforms:
            try:
                create_url = f"https://graph.facebook.com/v18.0/{config.IG_USER_ID}/media"
                r = requests.post(create_url, data={"image_url": image_url, "caption": captions.get('instagram', ''), "access_token": config.FB_PAGE_ACCESS_TOKEN})
                if 'id' in r.json():
                    r2 = requests.post(f"https://graph.facebook.com/v18.0/{config.IG_USER_ID}/media_publish", data={"creation_id": r.json()['id'], "access_token": config.FB_PAGE_ACCESS_TOKEN})
                    results['instagram'] = "✅ Posted" if 'id' in r2.json() else f"❌ Pub Fail: {r2.json()}"
                else: results['instagram'] = f"❌ Up Fail: {r.json()}"
            except Exception as e: results['instagram'] = str(e)
        return results

img_handler = ImageHandler()
agent = ContentAgent()
broadcaster = SocialBroadcaster()

# --- ROUTES ---
@app.route('/')
def home(): return render_template('home.html')

@app.route('/booking')
def booking_page(): return render_template('booking.html')

@app.route('/dashboard')
def dashboard():
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    total_impressions = db.session.query(func.sum(Post.impressions)).scalar() or 0
    stats = {"total_impressions": f"{total_impressions:,}", "engagement_rate": "5.2%"}
    return render_template('dashboard.html', posts=posts, stats=stats)

@app.route('/api/submit_booking', methods=['POST'])
def submit_booking():
    # CAPTURE ALL DATA
    name = request.form.get('name')
    phone = request.form.get('phone')
    location = request.form.get('location')
    date = request.form.get('date')
    message = request.form.get('message')

    if send_lead_email(name, phone, location, date, message):
        return render_template('booking.html', success=True)
    return "Error sending email.", 500

@app.route('/api/chat_generate', methods=['POST'])
def chat_generate():
    try:
        prompt = request.form.get('prompt')
        file = request.files.get('file')
        if not file and not prompt: return jsonify({"error": "Provide file or text"}), 400
        
        local_path, public_url = img_handler.process_request(file, prompt)
        captions = agent.generate_captions(local_path, prompt)
        return jsonify({"image_url": public_url, "captions": captions})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/confirm_post', methods=['POST'])
def confirm_post():
    data = request.json
    action = data.get('action')
    results = {}
    if action == 'instant':
        results = broadcaster.post_to_apis(data.get('platforms'), data.get('captions'), data.get('image_url'))
        status = "Published" if "✅" in str(results) else "Failed"
    else:
        status = f"Scheduled: {data.get('time')}"
    
    new_post = Post(platforms=",".join(data.get('platforms')), image_url=data.get('image_url'), caption=data.get('captions')['linkedin'], status=status, scheduled_time=data.get('time'))
    db.session.add(new_post)
    db.session.commit()
    return jsonify({"status": "success", "details": results})

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True, port=5000)